### ISSUE TITLE
Sleep data is missing

### ISSUE THREAD

**Issue by nightskyhub** [matinzd/react-native-health-connect#10]
@matinzd First of all very good work.
Sleep data is missing. I saw it is not implemented yet, Can you prioritise sleep data? Humble request.

**Comment by matinzd** [comment]
Hi

You can follow this pull request for the progress: 

https://github.com/matinzd/react-native-health-connect/pull/9

**Comment by matinzd** [comment]
🚀  v0.1.0-alpha.8 is now published under the alpha flag. 

Changelog:
https://github.com/matinzd/react-native-health-connect/releases/tag/v0.1.0-alpha.8
