### ISSUE TITLE
Gettign setPermissionDelegate error while implementing in React native 0.72 with Java folders

### ISSUE THREAD

**Issue by codewithhannan** [matinzd/react-native-health-connect#108]
I am using React Native 0.72 and have Java folders but the documentation shows kotlin configurations 

I have added everything from documentation but in

`HealthConnectPermissionDelegate.setPermissionDelegate(this);` it is not building my app.

Tried to run it with Android Studio it gives following error .
Anyone can help on that?
<img width="1131" alt="Screenshot 2024-06-27 at 6 39 13 PM" src="https://github.com/matinzd/react-native-health-connect/assets/61554305/3817518d-02de-4594-be28-67f311a0fa34">

**Comment by matinzd** [comment]
You can do this instead: 

```java
  @Override
  public void onCreate(@Nullable Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    // In order to handle contract results, we need to set the permission delegate.
    HealthConnectPermissionDelegate.INSTANCE.setPermissionDelegate(this, "com.google.android.apps.healthdata");
  }
```
