### ISSUE TITLE
minSdkVersion 24 cannot be smaller than version 26 declared in library

### ISSUE THREAD

**Issue by suyanksaraswat** [matinzd/react-native-health-connect#109]
**Describe the bug**
App is made on minSdkVersion 24 and compileSdkVersion 33.
When we try to use react-native-health-connect latest and older versions like 1.2.3, it gives a build error on running yarn android. Even once it asks us to upgrade packages, everytime build get some error. Also, this package asks to update .kt files, but as our verisons are older, it is in .java.

**To Reproduce**
1. set versions for minSdkVersion as 24, compileSdkVersion as 33, targetSdkVersion as 33 and react-native as 0.71.11
2. run yarn android
3. it will start showing build errors.

**Expected behavior**  
Build should work completely fine even for older react native versions.

**Screenshots**  
<img width="544" alt="image" src="https://github.com/matinzd/react-native-health-connect/assets/31132741/0ff7a6ed-8936-47e4-974b-f33360df76ff">
<img width="570" alt="image" src="https://github.com/matinzd/react-native-health-connect/assets/31132741/59ba8f9a-4f75-48c2-9f20-dba5aa069159">

**Environment:**
 - Health Connect Version: 1.2.3 and latest both.
 - React Native Version: 0.71.11
 - New architecture enabled: No
 - Using Expo: No

**Comment by matinzd** [comment]
Hey!

No, it's not supposed to work with with 25 or lower and it's clearly mentioned in the doc that Health Connect SDK requires android API 26 and higher:

https://github.com/matinzd/react-native-health-connect?tab=readme-ov-file#requirements
