### ISSUE TITLE
Body weight reading is missing

### ISSUE THREAD

**Issue by nandakishorepapila** [matinzd/react-native-health-connect#11]
When can we expect body weight reading feature support.

**Comment by matinzd** [comment]
You can follow this PR: https://github.com/matinzd/react-native-health-connect/pull/9

**Comment by matinzd** [comment]
🚀  v0.1.0-alpha.8 is now published under the alpha flag. 

Changelog:
https://github.com/matinzd/react-native-health-connect/releases/tag/v0.1.0-alpha.8
