### ISSUE TITLE
Lowest version of RN for version 1?

### ISSUE THREAD

**Issue by bitdelve** [matinzd/react-native-health-connect#113]
What is the lowest version of React Native that can be used for v1 of this project? I am working with a not very well maintained react native project that uses 0.59, and I need to transition from google fit to health connect. So far I have not had any luck integrating this.

**Comment by matinzd** [comment]
I do not recommend using v1 and RN 0.72 is nearing EOL. It's better for you to upgrade your project to the latest version of RN and use the latest version of health connect.

RN 0.59 is very old even before autolinking ...

**Comment by bitdelve** [comment]
> I do not recommend using v1 and RN 0.72 is nearing EOL. It's better for you to upgrade your project to the latest version of RN and use the latest version of health connect.
> 
> RN 0.59 is very old even before autolinking ...

Thank you. I came to that conclusion that upgrading needed to happen anyway. Working on that now.
