### ISSUE TITLE
Expo 48 plugin not working

### ISSUE THREAD

**Issue by thozh** [matinzd/react-native-health-connect#115]
**Describe the bug**
A build error occurs when trying to run the project on an Android device using Expo. The error is related to the `expo-health-connect` package in the Gradle build file.

```bash
1: Task failed with an exception.
-----------
* Where:
Build file '/Users/thomas/Documents/github_desktop/DoolENDO-MobileApp/node_modules/expo-health-connect/android/build.gradle' line: 9

* What went wrong:
A problem occurred evaluating project ':expo-health-connect'.
> Could not find method useCoreDependencies() for arguments [] on project ':expo-health-connect' of type org.gradle.api.Project.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
```

**To Reproduce**
1. Run `yarn run android`
2. Select a device/emulator
3. Wait for the build process to complete
4. See error in the console

**Expected behavior**
The app should build and run on the selected Android device without errors.

**Environment:**
- Health Connect Version: 2.1.0
- React Native Version: 0.71.14
- New architecture enabled: No
- Using Expo: Prebuild(Dev Client)

**Comment by matinzd** [comment]
`useCoreDependencies` was introduced in this [PR](https://github.com/expo/expo/pull/24201). This might have broken backward compatibility with older expo SDK versions. I suggest you to upgrade to latest Expo SDK. 

@kudo @ behenate Is there any workaround for this?

**Comment by thozh** [comment]
thanks for the suggestion, I had to upgrade to expo 51
