### ISSUE TITLE
Get aggregate steps for previous days?

### ISSUE THREAD

**Issue by bitdelve** [matinzd/react-native-health-connect#116]
Is it possible to get the total steps for each day in the past, but not combined? I.E. I want to get the steps from up to 14 days ago, but not all the steps for the 14 days. So I would want to retrieve all steps for 2024/07/12, then 2024/07/13, etc. From what I see it looks like i have to call aggregateRecord for each day. Or readRecords and then manually combine.

**Comment by taisuke-j** [comment]
Yes, same for our team which is currently actively developing a new health app integrating Health Connect. Any information about plans/ongoing development for `AggregateGroupByDurationRequest` would be highly appreciated.

https://developer.android.com/health-and-fitness/guides/health-connect/develop/aggregate-data#buckets
