### ISSUE TITLE
uses-sdk:minSdkVersion 23 cannot be smaller than version 26 declared in library [androidx.health.connect...]

### ISSUE THREAD

**Issue by realPrimoh** [matinzd/react-native-health-connect#121]
**Describe the bug**
Error is:
```
> Task :app:processDebugMainManifest FAILED
/Users/***/Projects/***/android/app/src/debug/AndroidManifest.xml Error:
        uses-sdk:minSdkVersion 23 cannot be smaller than version 26 declared in library [androidx.health.connect:connect-client:1.1.0-alpha06] /Users/***/.gradle/caches/transforms-4/ae4421fd35b079acbae3c31383d9ea69/transformed/jetified-connect-client-1.1.0-alpha06/AndroidManifest.xml as the library might be using APIs not available in 23
        Suggestion: use a compatible library with a minSdk of at most 23,
                or increase this project's minSdk version to at least 26,
                or use tools:overrideLibrary="androidx.health.connect.client" to force usage (may lead to runtime failures)

See https://developer.android.com/r/studio-ui/build/manifest-merger for more information about the manifest merger.
```

**To Reproduce**

Not sure. I just followed the installation instructions and got this error.

**Expected behavior**  

Ideally, my Android build should've built successfully.

**Environment:**
 - Health Connect Version: `"expo-health-connect": "^0.1.0",`
 - React Native Version:  "0.74.3"
 - New architecture enabled: Yes
 - Using Expo: Prebuild (Dev Client)

I'm getting issues with the Expo installation. Is there a step missing in the Expo installation guide or is it an issue with my project? Any help would be appreciated greatly. Thank you!

**Comment by realPrimoh** [comment]
I think in expo-health-connect, there's this line `minSdkVersion safeExtGet("minSdkVersion", 21)` which needs to be updated to `minSdkVersion safeExtGet("minSdkVersion", 26)`.

**Comment by realPrimoh** [comment]
Nvm. I just had to update my `build.gradle` to `minSdkVersion = Integer.parseInt(findProperty('android.minSdkVersion') ?: '26')`.

Sorry! Simple fix haha.

**Comment by dedomil** [comment]
Thank you for solution!
