### ISSUE TITLE
Execution failed for task ':expo-updates:kaptDebugKotlin'

### ISSUE THREAD

**Issue by ventsislavnikolov** [matinzd/react-native-health-connect#123]
**Describe the bug**
Trying to build the app with expo-updates installed as packages the build fail.

**To Reproduce**
Init a project with Expo
Install the react-native-health-connect and make the expo needed steps.
Install expo-updates package
Run the yarn android to run the app

**Expected behavior**  
The build to be successful.

**Screenshots**  
<img width="863" alt="Screenshot_1" src="https://github.com/user-attachments/assets/2a2c02f4-03e5-4bbe-a9e4-de40dc58079a">
<img width="1508" alt="Screenshot_2" src="https://github.com/user-attachments/assets/9e3b6568-9c39-418f-9fd8-fbd56176602d">

**Fix**
Removing the expo-update from package and clean the node_modules and yarn.lock and then install the packages.

**Environment:**
 - Health Connect Version: ^2.1.0
 - React Native Version: 0.74.3
 - Expo: 51.0.24
 - expo-updates: ~0.25.21
 - expo-health-connect: ^0.1.0
 - New architecture enabled: Dunno, using expo latest version
 - Using Expo: Prebuild(Dev Client)
 - PowerShell with Run as Admin

**Comment by matinzd** [comment]
First things first make sure you have jdk 17 installed.

Did you try removing health connect package and see if the build issue still exists? 

I also did some research and as you can see from the stacktrace the issue is not with health connect. If you search for this error in expo repository you could have found this issue that is resolved:

https://github.com/expo/expo/issues/28240

**Comment by ventsislavnikolov** [comment]
Oh sorry, your right. Its not releated to the Health Connect package and the problem was I was using Java 21 SDK. For expo managed flow without prebuild everything is fine, but after the prebuild command the problems is happening. The easy fix is to downgrade Java to 17, just remove SDK 21 and install SDK 17. Closing the issue and thanks!
