### ISSUE TITLE
Power returns empty array

### ISSUE THREAD

**Issue by gabrielgouv** [matinzd/react-native-health-connect#125]
**Describe the bug**
I've logged an exercise via Google Fit (manually) which includes Power. But the request to readRecords for Power returns an empty array. ExerciseSession comes normally... No errors on logcat, power permission enabled on Health Connect.

**To Reproduce**
1. Log a exercise via Google Fit (set a Power value)
2. Go to Health Connect
3. Click on Data and access > Activity > Power > See all entries
4. The Power entry is there (on Health Connect)
5. Code below returns empty array 

**Expected behavior**  
Should return an array of Power.

**Minimal Reproducible**  
```typescript
export const readAndroidSampleData = async () => {
  const isInitialized = await initialize();
  const grantedPermissions = await requestPermission([
    { accessType: "read", recordType: "ExerciseSession" },
    { accessType: "read", recordType: "Power" },
  ]);

  console.log("granted permissions:", grantedPermissions); // permission granted

  const exerciseRecords = await readRecords("ExerciseSession", {
    timeRangeFilter: {
      operator: "between",
      startTime: "2024-07-09T12:00:00.405Z",
      endTime: "2024-08-20T23:53:15.405Z",
    },
  });

  for (const exerciseRecord of exerciseRecords) {
    console.log("exerciseRecord:", exerciseRecord);

    const exercisePower = await readRecords("Power", {
      timeRangeFilter: {
        operator: "between",
        startTime: exerciseRecord.startTime,
        endTime: exerciseRecord.endTime,
      },
    });
    console.log("exercisePower:", exercisePower); // empty array

    console.log("=====================================");
  }
};
```

**Environment:**
 - Health Connect Version: 2024.07.11.00.release
 - React Native Version: 0.74.3
 - New architecture enabled: No
 - Using Expo: Prebuild(Dev Client)

**Comment by matinzd** [comment]
I manually added some power data and it's being returned when I want it.

<img width="1117" alt="Screenshot 2024-08-01 at 14 15 58" src="https://github.com/user-attachments/assets/c5ec9675-5ce7-415b-9309-ef2e522c9827">

**Comment by gabrielgouv** [comment]
Ah, I think I found the problem on my side. When I fetch the ExerciseRecord, it returns to me the endDate with 1ms less than the PowerRecord endDate:

ExerciseRecord:
```json
{
  "title": "Test Google Fit"
  "exerciseRoute": {},
  "exerciseType": 8,
  "laps": [],
  "metadata": {...},
  "notes": null,
  "segments": [],
  "endTime": "2024-08-01T00:50:00.237Z",   <-----
  "startTime": "2024-08-01T00:20:00.237Z"
}
```

PowerRecord:
```typescript
{
    "metadata": {...},
    "samples": [...],
    "endTime": "2024-08-01T00:50:00.238Z",   <-----
    "startTime": "2024-08-01T00:50:00.237Z"
  }
```

**Comment by matinzd** [comment]
Oh wow! :) Good to know.
