### ISSUE TITLE
GetChanges API support

### ISSUE THREAD

**Issue by ugurakin1** [matinzd/react-native-health-connect#135]
As far as I could tell from skimming the docs, is it correct that currently this library doesn't integrate changes API (i.e. `getChangesToken`/`getChanges` as mentioned on [the synchronize docs from Health Connect](https://developer.android.com/health-and-fitness/guides/health-connect/develop/sync-data#check-for-data-changes) )?  Is there a plan or any active work happening on that front?

**Comment by matinzd** [comment]
Hey!

This is implemented in v3.

https://github.com/matinzd/react-native-health-connect/releases/tag/v3.0.0
