### ISSUE TITLE
Sync is not happening

### ISSUE THREAD

**Issue by KSGoutami** [matinzd/react-native-health-connect#138]
I am a beginner to Android applications. I need to use Health Connect to collect real-time data for my research. I am using your code, but when i import the application I get an error. Could you please let me know is there any initial setting I need to make in android studio?

**Comment by matinzd** [comment]
Hi

You can follow the documentation [here](https://matinzd.github.io/react-native-health-connect/docs/intro). Hope that helps.

**Comment by KSGoutami** [comment]
I am facing the below error. Could you please help me in solving this?

* Where:
Script 'C:\Users\DELL\Downloads\react-native-health-connect-main\react-native-health-connect-main\example\node_modules\@react-native-community\cli-platform-android\native_modules.gradle' line: 413

* What went wrong:
A problem occurred evaluating script.
> Cannot run program "node" (in directory "C:\Users\DELL\Downloads\react-native-health-connect-main\react-native-health-connect-main\example\android"): CreateProcess error=2, The system cannot find the file specified

**Comment by matinzd** [comment]
You don't have node installed or your environment is not set up properly. If you are ono Windows and you just want to experiment this on Android I suggest you to use Native solution. Setting up React Native is a bit harder to follow. 

As you can see in the error your command line on Windows cannot detect where node installed or it's not installed at all. 

Going to close this issue. Feel free to move this to discussions section.

**Comment by KSGoutami** [comment]
Hello team,

Thank you for your reply.

I am using on windows. I want to use this android solution to collect the
health info from health connect app.

Could you please suggest the solution for me?


Thank you in advance.

Best Regards
Goutami Sheshappanavar
