### ISSUE TITLE
Caller doesn't have android.permission.health.READ_SLEEPto read to record typeclass android.health.connect.datatypes.SleepSessionRecord

### ISSUE THREAD

**Issue by RushitaRn25** [matinzd/react-native-health-connect#139]
**Describe the bug**

**To Reproduce**

**Expected behavior**  

**Screenshots**  

**Minimal Reproducible**  
Link to minimal reproducible code. It would be much easier for us to investigate the issue!

**Environment:**
 - Health Connect Version:3.1.0
 - React Native Version:  0.71.7
 - New architecture enabled: no
 - Using Expo: No
 - Android API Level: e.g API 34 (Android 14)

**Comment by matinzd** [comment]
As there is no reproduction and templated filled   I am gonna close this.

**Comment by KesoGizmoYoshi** [comment]
https://github.com/matinzd/react-native-health-connect?tab=readme-ov-file#installation

You need to add the changes to your MainActivity.kt.
