### ISSUE TITLE
Accessing the raw sensor data?

### ISSUE THREAD

**Issue by athenawisdoms** [matinzd/react-native-health-connect#14]
How can we access the raw sensor data from a Wear OS watch, like the Samsung Galaxy watch 4/5? 

Can it also be accessed in close to real time? I think it requires access to the [Sensors API](https://developers.google.com/fit/android/sensors), does `react-native-health-connect` provide access to the Sensors API?

And can we access the watch sensor data from the React native app running on a phone that is linked to the watch?

Thank you in advance!

**Comment by matinzd** [comment]
Hey,

In that case, you need to use Sensors API which is not provided by this library. This library is not intended to have that feature.
