### ISSUE TITLE
requestPermission never resolves

### ISSUE THREAD

**Issue by BlocknBoom123** [matinzd/react-native-health-connect#147]
**Describe the bug**
requestPermission method never resolves its promise. When I ask for permissions, I have to manually close and reopen the app again. There's no way to do a requestPermission([.....].then() as the promise never resolves.

**To Reproduce**
1. Call requestPermission
2. Click on Allow All permissions
3. The promise or logs within the 'then' never shows up as the promise never resolves, which affects my apps ability to tell the user if their permissions were granted or not. They have to restart the entire app and then use getGrantedPermissions to check permissions.

**Expected behavior**  
requestPermission should resolve and alert the app immediately that the promise resolved when clicking Allow all/Allow.

**Screenshots**  
![image](https://github.com/user-attachments/assets/396f3217-ab0c-47a7-98ae-3a74c6da9a6e)

**Minimal Reproducible**  
Link to minimal reproducible code. It would be much easier for us to investigate the issue!

**Environment:**
 - Health Connect Version: ^3.1.0
 - React Native Version: ^0.71.15
 - New architecture enabled: ? No
 - Using Expo: No
 - Android API Level: Android 14

**Comment by heritvithalani19** [comment]
I faced the same issue .requestPermission as the promise never resolves.
try {
const androidPermission = await requestPermission([
{ accessType: 'read', recordType: 'HeartRate' },
]);
console.log('Response:', androidPermission); // Debugging line
} catch (error) {
console.log(error)
}

**Comment by matinzd** [comment]
This issue has been opened many times and I have responded to it in different issues. Please make sure to follow the documentation and setup permission delegate in your MainActivity. Not setting that up will result in the promise not being resolved.

**Comment by heritvithalani19** [comment]
> MainActivity
import dev.matinzd.healthconnect.permissions.HealthConnectPermissionDelegate; // import statement 

// In order to handle permission contract results, we need to set the permission delegate.
 HealthConnectPermissionDelegate.INSTANCE.setPermissionDelegate(this,"com.google.android.apps.healthdata");

**Comment by BlocknBoom123** [comment]
> > MainActivity
> > import dev.matinzd.healthconnect.permissions.HealthConnectPermissionDelegate; // import statement
> 
> // In order to handle permission contract results, we need to set the permission delegate. HealthConnectPermissionDelegate.INSTANCE.setPermissionDelegate(this,"com.google.android.apps.healthdata");

I also use this as my MainActivity is used in a Java file, not a Kotlin file. 
HealthConnectPermissionDelegate.INSTANCE.setPermissionDelegate(this, "com.google.android.apps.healthdata");

**Comment by matinzd** [comment]
Please upgrade to RN 0.71.16 or any latest patch on each RN release.

There was an issue in the react native core which got fixed.

https://github.com/facebook/react-native/releases/tag/v0.71.16

**Comment by heritvithalani19** [comment]
> Please upgrade to RN 0.71.16 or any latest patch on each RN release.
> 
> There was an issue in the react native core which got fixed.
> 
> https://github.com/facebook/react-native/releases/tag/v0.71.16
> 
> You need to have this fix in order for this to work:
> 
> [facebook/react-native#42478](https://github.com/facebook/react-native/pull/42478)

Please update the documentation accordingly. The document currently states version 0.71 and higher.

**Comment by matinzd** [comment]
You are right but upgrading to latest patch is something that most people do. I will update the docs accordingly.

**Comment by heritvithalani19** [comment]
> You are right but upgrading to latest patch is something that most people do. I will update the docs accordingly.

This solution was incredibly helpful for me in getting it done. I truly appreciate your efforts and the time you took.

Thank you!

**Comment by matinzd** [comment]
Docs is now updated.

**Comment by matinzd** [comment]
Let me know if that fixed the issue so I can close this issue.

**Comment by heritvithalani19** [comment]
I tried with apply patch but it's not solved yet. I am using react-native version 0.71.11

**Comment by matinzd** [comment]
Why don't you upgrade to latest 71 patch? 

Here is how to upgrade your project:

https://react-native-community.github.io/upgrade-helper/?from=0.71.11&to=0.71.19

**Comment by BlocknBoom123** [comment]
I upgraded to the latest 71 patch and my app crashes (... has stopped working) when I call requestPermission now. The screen goes black and tells me if I want to wait for the app to respond or close it. When I reopen it, the permissions are set, but obviously this is not how I want to handle the app.

**Comment by matinzd** [comment]
Can you create a minimal reproducible and share the link here where this is happening?

**Comment by ryeker-herndon-lark** [comment]
This is also happening for me on React Native 0.73.6.

**Comment by BlocknBoom123** [comment]
@matinzd It's working now thanks. I can't share the code as its from my company but this line was commented out so uncommenting it fixes it.
super.onRequestPermissionsResult(requestCode, permissions, grantResults);

**Comment by matinzd** [comment]
> @matinzd It's working now thanks. I can't share the code as its from my company but this line was commented out so uncommenting it fixes it.
> 
> super.onRequestPermissionsResult(requestCode, permissions, grantResults);

Where is that code? By sharing minimal reproducible I mean you create a whole new project and you copy and paste your related files in there without any private code. 
Of course I am not asking for your company's source code.

**Comment by BlocknBoom123** [comment]
I have a BaseActivity class that extends AppCompatActivity and that's where the line was commented.

 @Override
    public void onRequestPermissionsResult(int requestCode, String[] permissions, int[] grantResults) {
       // super.onRequestPermissionsResult(requestCode, permissions, grantResults);
        mDelegate.onRequestPermissionsResult(requestCode, permissions, grantResults);
    }

**Comment by heritvithalani19** [comment]
@matinzd 
Thank you for your prompt support. After upgrading to the latest patch of React Native, everything is working perfectly.
