### ISSUE TITLE
Task ':react-native-health-connect:compileDebugAidl' FAILED

### ISSUE THREAD

**Issue by juskk** [matinzd/react-native-health-connect#15]
Hi there, at first I'd like to thank for this library, just in time. I'm trying to build my project after installing this lib, but it fails.

My react native version was 0.64.0, but I saw the comment that it's better to use this lib with version 67+, so I manually upgraded it. Currently that's my setup:
 - Health Connect Version: 1.0.0
 - React Native Version: 0.70.0
 - New architecture enabled: No
I also tried to run this lib having my react native version 0.64.0, had the same error.

I'm not strong with the native part, so may be you could have any suggestions what could be wrong. Please tell me if I need to share some more info, first time making a report.

<img width="827" alt="image" src="https://user-images.githubusercontent.com/71719203/229303230-586fe608-bd33-4f8a-b716-7e4e99d8bd99.png">
<img width="849" alt="image" src="https://user-images.githubusercontent.com/71719203/229303426-267d9b90-4458-40ee-b180-37032730a4f7.png">

Thank you for your time and expertise.

**Comment by matinzd** [comment]
Hi 👋 
Which JDK and gradle version are you using?

**Comment by juskk** [comment]
Gradle 7.2, jdk version "11.0.11" 2021-04-20. As for providing the sample it could be a problem, do you need the whole project or just some core files?

**Comment by matinzd** [comment]
> Gradle 7.2, jdk version "11.0.11" 2021-04-20. As for providing the sample it could be a problem, do you need the whole project or just some core files?

You can just provide a small repro that contains lottie. No need for whole project.

**Comment by juskk** [comment]
The problem is I'm trying to integrate the lib on a real project, don't think I'm allowed to share it, and simply creating another empty project trying to reproduce the problem could be problematic. May be you have any suggestions to which part/tool the problem could be related?

**Comment by matinzd** [comment]
I would suggest you installing this in a new fresh react native project and see if you still have an issue. If you face an issue even when you install it on a fresh new project, then there is something wrong here. There might be some configuration issues in your own project which you need to look into it since I don't have access to your whole project.

**Comment by matinzd** [comment]
> @matinzd Same Issue in my project

Can you send me the small reproduction repository that contains the error?

**Comment by abidjamil** [comment]
@matinzd Actually I am using it in my project, I can't share the repo

**Comment by matinzd** [comment]
> @matinzd Actually I am using it in my project, I can't share the repo

As I said, you can create a new repo that contains this error. I cannot help you with your project as I cannot see the configuration as well as the dependencies you are using that may result in conflict. 

Please try creating another repo and try to reproduce it and send it here.

**Comment by juskk** [comment]
@abidjamil upgrade your project to version 0.71.0+.
the problem I had was related to react native version. I've seen the lib is compatible with react native 68+, but in my case it started working only when I upgraded my app to version 0.71.0.

**Comment by ClementAGIL** [comment]
I have exactly the same problem, I am in version 0.68.2. I am not in a position where I can easily upgrade to 0.71.0. I cannot share my repo

**Comment by matinzd** [comment]
> I have exactly the same problem, I am in version 0.68.2. I am not in a position where I can easily upgrade to 0.71.0. I cannot share my repo

Can you try upgrading to [0.68.6](https://www.npmjs.com/package/react-native/v/0.68.6)? This can be easy and it just contains some patches from RN team.

**Comment by matinzd** [comment]
Please refer to this issue: https://github.com/facebook/react-native/issues/35210

I will mark this as resolved.
