### ISSUE TITLE
Error on Expo SDK v50: Could not find method publishing() for arguments

### ISSUE THREAD

**Issue by PercipioDrew** [matinzd/react-native-health-connect#150]
**Describe the bug**

After installing `expo-health-connect` in an Expo v50 application, I get the following error when running `npx expo run:android`.

```
Could not find method publishing() for arguments [ExpoModulesCorePlugin_ckr63lb0mk88jgtdlukbc772b$_run_closure2$_closure5$_closure7@76f6a9ee] on project ':expo-health-connect' of type org.gradle.api.Project
```

**To Reproduce**

[Minimal Reproducible code example](https://github.com/PercipioDrew/expo-health-connect-example).

The following steps outline how the above project was created, such as if you wanted to recreate the problem from scratch.

To create a new Expo project with a specific version such as Expo SDK 50 rather than latest/51:
```
npx create-expo-app expo-health-example --template blank@sdk-50
```

Health Connect won't work with Expo Go, so have to switch to the Dev Client instead:
```
npx expo install expo-dev-client
```
and run on Android via the following, which should succeed, since this is a stock Expo 50 project:
```
npx expo run:android --device
```

Now install the dependencies (following [this guide](https://matinzd.github.io/react-native-health-connect/docs/get-started#expo-installation)):
```
npx expo install expo-health-connect
npm install react-native-health-connect
```

Then running `npx expo run:android --device` again will result in the above error `Could not find method publishing() for arguments`.  

Running through these same steps *using Expo v51 _will_ work* (You can follow the same steps as above, but the first command should be `npx create-expo-app expo-health-example --template blank@sdk-51`.  Alternatively, in the [Minimal Reproducible code example](https://github.com/PercipioDrew/expo-health-connect-example) you can switch to the `expo-51` branch, and it will work.)

**Expected behavior**  

Start an application using `expo-health-connect` on Android, using Expo v50.

**Screenshots**  

![expo-health-connect-error](https://github.com/user-attachments/assets/ab9badf5-c419-43f5-aa68-2d8b93b69fa2)

**Environment:**
 - Health Connect Version: 2024.08.22.00.release
 - React Native Version: 0.73.6
 - New architecture enabled: No
 - Using Expo: Prebuild(Dev Client)
 - Android API Level: Android 14

My `package.json` references these lib versions:
```
"expo-health-connect": "^0.1.1",
"react-native-health-connect": "^3.1.0",
```
- Node v20.9.0

**Comment by manan-schmooze** [comment]
Did you find any solution?

**Comment by matinzd** [comment]
Hey!

Thank you for your thorough explanation. This is one of the most promising and well-presented issues I've come across in this repository.

Let's dive in.

It seems like there is a problem with newly created expo modules not being compatible with sdk-50. I sent a fix in expo repository for sdk-50 and hope they merge it. 

If not you can use this patch `expo-modules-core+1.11.13.patch`:

```patch 
diff --git a/node_modules/expo-modules-core/android/ExpoModulesCorePlugin.gradle b/node_modules/expo-modules-core/android/ExpoModulesCorePlugin.gradle
index 4a413e3..2fc1cde 100644
--- a/node_modules/expo-modules-core/android/ExpoModulesCorePlugin.gradle
+++ b/node_modules/expo-modules-core/android/ExpoModulesCorePlugin.gradle
@@ -58,6 +58,10 @@ ext.applyKotlinExpoModulesCorePlugin = {
 }
 
 ext.useExpoPublishing = {
+  if (!project.plugins.hasPlugin('maven-publish')) {
+    apply plugin: 'maven-publish'
+  }
+  
   afterEvaluate {
     publishing {
       publications {
```

**Comment by matinzd** [comment]
Here is the updated patch:

```patch
diff --git a/node_modules/expo-modules-core/android/ExpoModulesCorePlugin.gradle b/node_modules/expo-modules-core/android/ExpoModulesCorePlugin.gradle
index 4a413e3..e6e1342 100644
--- a/node_modules/expo-modules-core/android/ExpoModulesCorePlugin.gradle
+++ b/node_modules/expo-modules-core/android/ExpoModulesCorePlugin.gradle
@@ -54,10 +54,21 @@ class KotlinExpoModulesCorePlugin implements Plugin<Project> {
 }
 
 ext.applyKotlinExpoModulesCorePlugin = {
+  try {
+    // Tries to apply the kotlin-android plugin if the client project does not apply yet.
+    // On previous `applyKotlinExpoModulesCorePlugin`, it is inside the `project.buildscript` block.
+    // We cannot use `project.plugins.hasPlugin()` yet but only to try-catch instead.
+    apply plugin: 'kotlin-android'
+  } catch (e) {}
+
   apply plugin: KotlinExpoModulesCorePlugin
 }
 
 ext.useExpoPublishing = {
+  if (!project.plugins.hasPlugin('maven-publish')) {
+    apply plugin: 'maven-publish'
+  }
+  
   afterEvaluate {
     publishing {
       publications {
```

**Comment by matinzd** [comment]
Please upgrade to Expo v[50.0.21](https://www.npmjs.com/package/expo/v/50.0.21).

**Comment by PercipioDrew** [comment]
That worked, thanks so much @matinzd!

Just for reference for anyone else encountering the issue: I did need to clear out the existing `android` directory, so the commands to get this working were:
```shell
npm install expo@50.0.21
rm -rf android
npm run android
```
