### ISSUE TITLE
Wrong recordType value returned for ExerciseSession permission

### ISSUE THREAD

**Issue by mphill** [matinzd/react-native-health-connect#152]
**Describe the bug**

When requesting permissions, the wrong string value is returned:

`const permissions = await getGrantedPermissions();`

`=> [{"accessType": "write", "recordType": "Exercise"}]`

The typescript type for `Permission.recordType` is  `ExerciseSession`

**Environment:**
 - Health Connect Version: 3.1.0
 - React Native Version: 0.74.5
 - New architecture enabled: No
 - Using Expo: Prebuild(Dev Client)
 - Android API Level: API 34 (Android 14)

**Comment by matinzd** [comment]
This should be fixed in v3.1.1.
