### ISSUE TITLE
How to use AggregateGroupByPeriodRequest and AggregateGroupByDurationRequest?

### ISSUE THREAD

**Issue by nightskyhub** [matinzd/react-native-health-connect#16]
How can we aggregate steps data for day.
Let's say I want to fetch data for past 7 days and want count of total steps per day.

**Comment by matinzd** [comment]
Hi

Yes! You can find it in the documentation below:
https://matinzd.github.io/react-native-health-connect/docs/api/methods/aggregateRecord

**Comment by matinzd** [comment]
Hi

Yes! You can find it in the documentation below:

https://matinzd.github.io/react-native-health-connect/docs/api/methods/aggregateRecord

Each record type has its own result type. You can try `Steps` record and see what results you'll get. If you want for each day, you need to chunk below example into 7 different days. 

Example:

```ts
aggregateRecord({
  recordType: 'Steps',
  timeRangeFilter: {
    operator: 'between',
    startTime: new Date(
      new Date().getTime() - 7 * 24 * 60 * 60 * 1000 // 7 days
    ).toISOString(),
    endTime: new Date().toISOString(),
  },
}).then((result) => {
  console.log(result.COUNT_TOTAL);
});
```

**Comment by matinzd** [comment]
Thanks for pointing these out. I think these were added in the recent versions and it's not supported yet. I will add those to the roadmap.

**Comment by chganesh** [comment]
@matinzd @nightskyhub 
How can we aggregate steps data for day and All vitals .
Let's say I want to fetch data for past 7 and 30  days and want count of total steps per day.

i want display all vitals and steps and burned calories sleep ...etc is is possible to display all this stuff
please help on this 

thanks in advance

**Comment by cannyRamji** [comment]
Hi @matinzd,  When we can expect this feature, we are facing performance issue due to this. iOS by default provide payload in 1 Hour range

https://github.com/matinzd/react-native-health-connect/issues/16#issuecomment-1497233505

**Comment by shesellsanctuary** [comment]
Hello @matinzd, Is there a plan to fulfil this feature?

**Comment by matinzd** [comment]
If someone is up for sponsoring I will dedicate some time to implement it. Otherwise you can fork the project and add it yourself.

**Comment by taisuke-j** [comment]
@matinzd Just made a PR integrating `aggregateGroupByPeriod` API. Would be great if you could take a look

https://github.com/matinzd/react-native-health-connect/pull/157
