### ISSUE TITLE
iOS Pod install fails

### ISSUE THREAD

**Issue by olehtalanov** [matinzd/react-native-health-connect#168]
There is an error when trying to install Pods.

UnsupportedGenericParserError: Module NativeHealthConnect: Unrecognized generic type 'TimeRangeSlicer' in NativeModule spec.

Downgrade to 3.1.2 works so far. 

P.S. Tried to exlude package with react-native.config.js also didn't work.

**Comment by matinzd** [comment]
Have you turned on  new architecture? It seems like codegen is trying to build and it's failing. I will release a fix for this soon but for a workaround change this line to Object and remove the import:

https://github.com/matinzd/react-native-health-connect/blob/8c2cf3998ae2bdb12b2eb723416a676208e1a6d8/src/NativeHealthConnect.ts#L39
