### ISSUE TITLE
readRecords returning only 1 record and aggregateRecord dont match with it

### ISSUE THREAD

**Issue by krisidmisso** [matinzd/react-native-health-connect#18]
**Describe the bug**
1. `readRecords` doesnt match the data returned by `aggregateRecord`(0)
2. `readRecords` returns only 1 record regardless of the date range. Is it relared to the HealthConnect or my app installation/permission date?

Wearable: Samsung Watch 3
App: Samsung Health + Health Connect(latest)

**To Reproduce**
```
readRecords('Steps', {
  timeRangeFilter: {
    operator: 'between',
    startTime: '2023-04-01T04:00:00Z',
    endTime: new Date().toISOString(),
  },
})
  .then(value => console.log(value))
  .catch(e => console.log(e));

aggregateRecord({
  recordType: 'Steps',
  timeRangeFilter: {
    operator: 'between',
    startTime: new Date(
      new Date().getTime() - 7 * 24 * 60 * 60 * 1000, // 7 days
    ).toISOString(),
    endTime: new Date().toISOString(),
  },
}).then(result => {
  console.log(result);
});
```

**Expected behavior**
- `readRecords` should return all records for entered date range
- The total steps should be the same on both methods

**Screenshots**
<img width="1058" alt="image" src="https://user-images.githubusercontent.com/9657055/235835485-87126d8d-4cfc-4ebd-873b-ec89aa0d65d4.png">
**Environment:**
 - Health Connect Version: 1.0.1
 - React Native Version: 0.69.7
 - New architecture enabled: No

**Comment by matinzd** [comment]
Make sure that your device time is set properly. Sometimes if you keep the emulator running for a long time the timezone will go out of sync.

**Comment by krisidmisso** [comment]
I am testing on a real device: Samsung S22Ultra with Android 13. After adding some more data I get a number in `aggregatedRecord` but it still does not match the `readRecords`. Also I still see just 1 record:
<img width="415" alt="image" src="https://user-images.githubusercontent.com/9657055/235964823-313f5e6a-d55d-4bb6-bddb-ef26045f6eef.png">

**Comment by matinzd** [comment]
> I am testing on a real device: Samsung S22Ultra with Android 13. After adding some more data I get a number in `aggregatedRecord` but it still does not match the `readRecords`. Also I still see just 1 record:
> 
> <img width="415" alt="image" src="https://user-images.githubusercontent.com/9657055/235964823-313f5e6a-d55d-4bb6-bddb-ef26045f6eef.png">
> 
> 

Interesting! 
I will take a look into that when I find some time.

**Comment by krisidmisso** [comment]
Can confirm that I can only get data from the installation date of Health Connect. `aggregateRecords` still not matching for the same `timeRangeFilter`: 

<img width="736" alt="image" src="https://user-images.githubusercontent.com/9657055/236334384-e20a2e22-9e12-4e6b-a49c-4e7de8a7c32b.png">

**Comment by matinzd** [comment]
can confirm that data will be returned starting from the date of Health Connect's installation. However, there appears to be a bug in the Health Connect service. Although I can view the data on the Health Connect app, I'm unable to retrieve it using the client query function.

**Comment by matinzd** [comment]
To be tracked here by Google: https://issuetracker.google.com/u/1/issues/281942487

**Comment by matinzd** [comment]
After some investigation:

https://issuetracker.google.com/u/1/issues/274144813#comment6

> At the moment, there isn't a way to read data past up to 30 days before the first successful permissions request, but it is something that is being actively explored.
> 
> I'll share this use case back with the team to help better inform their discussion.
>

**Comment by krisidmisso** [comment]
I will test it again when an update of the app is issued. Thank you
