### ISSUE TITLE
Google play store is rejecting the app

### ISSUE THREAD

**Issue by SunnyBalani92** [matinzd/react-native-health-connect#190]
We are using the latest version 3.3.1 of this library. Everything is working fine but when we are releasing the app for production, google play console is rejecting the app because of the below reasons

Health Connect by Android Permissions policy: Inappropriate Health Connect Access Requested
Status
Update rejected
Previous version available on Google Play
Rejected
Dec 16, 2024, 8:04 PM
The [Health Connect Permissions](https://support.google.com/googleplay/android-developer/answer/9888170?sjid=13333536472157497015-NA#ahp) Google Play Policy specifies that you may only request access to permissions that are critical to implementing your application functionality. Requesting permissions that are not critical to implementing your application’s functionality are a violation of the policy.

Please ensure you are requesting the minimum necessary scopes.

[Google Play](https://support.google.com/googleplay/android-developer/answer/9888170?sjid=13333536472157497015-NA#ahp) policy requires that your application only uses the minimum scopes necessary for functionality. After review of your application we determined that your application does not require the following permissions

SleepSession

How to fix
Please remove these permissions you are requesting access to across all your app bundles, or resubmit the application for review with thorough justification as to why you require these scopes.

For helpful resources, you can:

Learn more about the [Health Connect Permissions](https://support.google.com/googleplay/android-developer/answer/9888170?sjid=13333536472157497015-NA#ahp) policy.
Read through our Help Center for more details and [FAQs](https://developer.android.com/health-and-fitness/guides/health-connect/develop/frequently-asked-questions).
Learn how to [Get started with Health Connect](https://developer.android.com/health-and-fitness/guides/health-connect/develop/get-started).
Check [Google Play SDK Index](https://developer.android.com/distribute/sdk-index) to see if your SDK provider has shared a link to their Data safety guidance. [Review](https://developer.android.com/guide/topics/data/collect-share) how any third-party code (such as third-party libraries or SDKs) in your app collects and shares user data, including health connect data.

If we remove the sleepsession permission, then we are not able to fetch sleep data from health connect.

Can you please suggest on what is going wrong here?

**Comment by SunnyBalani92** [comment]
@matinzd  Is there any resolution for this?

**Comment by matinzd** [comment]
Hi!

I am not sure how I can help you with this? It's clearly stated what Google Play wants and it instructs you what to do. There is nothing I can help you here.

You need to submit requested scopes in the play console for approval then you'll be able to submit app afterwards. Please follow the links provided in the rejection.

**Comment by tigerasks** [comment]
@SunnyBalani92 were you able to resolve this? we are running into a similar issue where google rejects us for requesting permissions that we clearly use. (Steps and ExerciseSession, in our case)
