### ISSUE TITLE
Cannot resolve 'main' module

### ISSUE THREAD

**Issue by grahamyesfit** [matinzd/react-native-health-connect#2]
```
react-native:  0.64.0
react: 17.0.1
react-native-health-connect: 0.0.1
```

I have followed the install instructions, but when I run my react-native project (using `react-native run-android`) I receive the following error:

```
Error: While trying to resolve module `react-native-health-connect` from file `...src\containers\HealthConnect\index.js`, the package `...node_modules\react-native-health-connect\package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved
```

Any assistance would be greatly appreciated.

Thanks,
Graham.

**Comment by matinzd** [comment]
Hi @grahamyesfit 

Please install it from `alpha` channel.

```
yarn add lottie-react-native@alpha

```

I will close this issue and let me know if it persists.

However, be aware not all records are implemented in alpha channel.
