### ISSUE TITLE
upgrade to 1.1.0-alpha03

### ISSUE THREAD

**Issue by matinzd** [matinzd/react-native-health-connect#23]
- [x] Update `ExerciseSessionRecord` to add `segments` and `laps`
- [x] Update `SleepSessionRecord` to add `stages` and remove `SleepStageRecord`
- [x] Add `ExerciseRoute`
- [ ] #34

Commits: https://android.googlesource.com/platform/frameworks/support/+log/refs/heads/androidx-main/health/connect/connect-client/src/main/java/androidx/health/connect/client

Changelog (Not containing all changes): https://developer.android.com/jetpack/androidx/releases/health-connect

**Comment by ahmad-crossplatform** [comment]
Any news about this one ?  :)
