### ISSUE TITLE
Permission issue

### ISSUE THREAD

**Issue by chganesh** [matinzd/react-native-health-connect#28]
**Describe the bug**

android.permission.health.WRITE_ACTIVE_CALORIES_BURNED,android.permission.health.READ_ACTIVE_CALORIES_BURNED added to android manifest 
added these two permission but request sample permission and granted permissions getting empty array
 {"result": true}
 LOG  SDK is available
 LOG  Granted permissions on request  {"permissions": []}
 LOG  Granted permissions  {"permissions": []} 

**To Reproduce**

Possible Unhandled Promise Rejection (id: 0):
Object {
  "code": "PERMISSION_ERROR",
  "message": "[android.permission.health.WRITE_ACTIVE_CALORIES_BURNED] is not declared!",
  "nativeStackAndroid": Array [],
  "userInfo": null,
}

**Expected behavior**
I want to get all values like steps calories and vitals Please help me one this 

**Environment:**
 "react": "18.2.0",
    "react-native": "0.72.1",
    "react-native-health-connect": "^1.0.4"
 - New architecture enabled: Yes

**Comment by chganesh** [comment]
Hi @matinzd  in integrated your example application code to my react native sample application given those two permission clicked one by one actions like
Initialize
Open Health Connect settings
Check availability
Request sample permissions
Get granted permissions
Read sample data

response 
Possible Unhandled Promise Rejection (id: 0):
Object {
"code": "PERMISSION_ERROR",
"message": "[android.permission.health.WRITE_ACTIVE_CALORIES_BURNED] is not declared!",
"nativeStackAndroid": Array [],
"userInfo": null,
}

**Comment by matinzd** [comment]
Can you provide a reproduction repo and remove the irrelevant/private code?

**Comment by chganesh** [comment]
//App.tsx
----------
import * as React from 'react';
import { Button, StyleSheet, View } from 'react-native';
import {
  aggregateRecord,
  getGrantedPermissions,
  initialize,
  insertRecords,
  getSdkStatus,
  readRecords,
  requestPermission,
  revokeAllPermissions,
  SdkAvailabilityStatus,
  openHealthConnectSettings,
  readRecord,
} from 'react-native-health-connect';

export default function App() {
  const initializeHealthConnect = async () => {
    const result = await initialize();
    console.log({ result });
  };

  const checkAvailability = async () => {
    const status = await getSdkStatus();
    if (status === SdkAvailabilityStatus.SDK_AVAILABLE) {
      console.log('SDK is available');
    }

    if (status === SdkAvailabilityStatus.SDK_UNAVAILABLE) {
      console.log('SDK is not available');
    }

    if (
      status === SdkAvailabilityStatus.SDK_UNAVAILABLE_PROVIDER_UPDATE_REQUIRED
    ) {
      console.log('SDK is not available, provider update required');
    }
  };

  const insertSampleData = () => {
    insertRecords([
      {
        recordType: 'ActiveCaloriesBurned',
        energy: { unit: 'kilocalories', value: 10000 },
        startTime: '2023-01-09T09:00:00.000Z',
        endTime: '2023-01-09T10:00:00.000Z',
      },
    ]).then((ids) => {
      console.log('Records inserted ', { ids });
    });
  };

  const readSampleData = () => {
    readRecords('ActiveCaloriesBurned', {
      timeRangeFilter: {
        operator: 'between',
        startTime: '2023-01-09T00:00:00.000Z',
        endTime: '2023-01-09T23:59:59.999Z',
      },
    }).then((result) => {
      console.log('Retrieved records: ', JSON.stringify({ result }, null, 2));
    });
  };

  const readSampleDataSingle = () => {
    readRecord(
      'ActiveCaloriesBurned',
      'a7bdea65-86ce-4eb2-a9ef-a87e6a7d9df2'
    ).then((result) => {
      console.log('Retrieved record: ', JSON.stringify({ result }, null, 2));
    });
  };

  const aggregateSampleData = () => {
    aggregateRecord({
      recordType: 'ActiveCaloriesBurned',
      timeRangeFilter: {
        operator: 'between',
        startTime: '2023-01-09T00:00:00.000Z',
        endTime: '2023-01-09T23:59:59.999Z',
      },
    }).then((result) => {
      console.log('Aggregated record: ', { result });
    });
  };

  const requestSamplePermissions = () => {
    requestPermission([
      {
        accessType: 'read',
        recordType: 'ActiveCaloriesBurned',
      },
      {
        accessType: 'write',
        recordType: 'ActiveCaloriesBurned',
      },
    ]).then((permissions) => {
      console.log('Granted permissions on request ', { permissions });
    });
  };

  const grantedPermissions = () => {
    getGrantedPermissions().then((permissions) => {
      console.log('Granted permissions ', { permissions });
    });
  };

  return (
    <View style={styles.container}>
      <Button title="Initialize" onPress={initializeHealthConnect} />
      <Button
        title="Open Health Connect settings"
        onPress={openHealthConnectSettings}
      />
      <Button title="Check availability" onPress={checkAvailability} />
      <Button
        title="Request sample permissions"
        onPress={requestSamplePermissions}
      />
      <Button title="Get granted permissions" onPress={grantedPermissions} />
      <Button title="Revoke all permissions" onPress={revokeAllPermissions} />
      <Button title="Insert sample data" onPress={insertSampleData} />
      <Button title="Read sample data" onPress={readSampleData} />
      <Button title="Read specific data" onPress={readSampleDataSingle} />
      <Button title="Aggregate sample data" onPress={aggregateSampleData} />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    rowGap: 16,
  },
  box: {
    width: 60,
    height: 60,
    marginVertical: 20,
  },
});

package.json
-------------
{
  "name": "HealthSample",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "lint": "eslint .",
    "start": "react-native start",
    "test": "jest"
  },
  "dependencies": {
    "react": "18.2.0",
    "react-native": "0.72.1",
    "react-native-health-connect": "^1.0.4"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@babel/preset-env": "^7.20.0",
    "@babel/runtime": "^7.20.0",
    "@react-native/eslint-config": "^0.72.2",
    "@react-native/metro-config": "^0.72.7",
    "@tsconfig/react-native": "^3.0.0",
    "@types/metro-config": "^0.76.3",
    "@types/react": "^18.0.24",
    "@types/react-test-renderer": "^18.0.0",
    "babel-jest": "^29.2.1",
    "eslint": "^8.19.0",
    "jest": "^29.2.1",
    "metro-react-native-babel-preset": "0.76.5",
    "prettier": "^2.4.1",
    "react-test-renderer": "18.2.0",
    "typescript": "4.8.4"
  },
  "engines": {
    "node": ">=16"
  }
}
//manifest.xml
--------------
<manifest xmlns:android="http://schemas.android.com/apk/res/android">

    <uses-permission android:name="android.permission.INTERNET" />
    
    <uses-permission android:name="android.permission.health.READ_ACTIVE_CALORIES_BURNED" />
    <uses-permission android:name="android.permission.health.WRITE_ACTIVE_CALORIES_BURNED" />

    <application
      android:name=".MainApplication"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:roundIcon="@mipmap/ic_launcher_round"
      android:allowBackup="false"
      android:theme="@style/AppTheme">
      <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenLayout|screenSize|smallestScreenSize|uiMode"
        android:launchMode="singleTask"
        android:windowSoftInputMode="adjustResize"
        android:exported="true">
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
      </activity>
    </application>
</manifest>

**Comment by chganesh** [comment]
@matinzd any solution for this one.

**Comment by matinzd** [comment]
> @matinzd any solution for this one.

Please follow the docs carefully:

https://matinzd.github.io/react-native-health-connect/docs/permissions

You forgot to add `intent-filter` inside the activity tag.

**Comment by chganesh** [comment]
@matinzd working fine for me. thank you.
