### ISSUE TITLE
Expo 49 failing 'expo doctor' because of @expo/config-plugins@6.0.2 dependency

### ISSUE THREAD

**Issue by robertherber** [matinzd/react-native-health-connect#29]
When using Expo 49 and installing react-native-health-connect the command `expo-doctor` fails because of the @expo/config-plugins dependency version.

This is the error:
<img width="498" alt="Screenshot 2023-07-16 at 22 33 02" src="https://github.com/matinzd/react-native-health-connect/assets/1467411/9ff5eefb-043d-4864-9e52-adb14e066fc5">

To reproduce: 
1. initialize a new Expo project with Expo 49
2. Install `react-native-health-connect`
3. Run `expo-doctor`

I'm guessing the dependency @expo/config-plugins could be moved to devDependencies - potentially supplemented with an peerDependency with a loose version?

**Comment by matinzd** [comment]
Yeah, it makes sense. I will move it to peerDependencies.

**Comment by matinzd** [comment]
Included in the [release](https://github.com/matinzd/react-native-health-connect/releases/tag/v1.1.0).

**Comment by robertherber** [comment]
Thanks for the quick response and fix @matinzd :)
