### ISSUE TITLE
Improvement Suggestions

### ISSUE THREAD

**Issue by philipp65** [matinzd/react-native-health-connect#3]
First of all, **thank you** very much for this library. Awesome work, clean code!

I found some minor things while using it since yesterday:
## Documentation <-> Readme
Readme: `yarn add react-native-health-connect@alpha`
Doc: `yarn add react-native-health-connect` (+ alpha note missing)

## Documentation Requirements
I also had to upgrade `ext.kotlinVersion = "1.8.0"`

## Health Connect alpha10 migration
Some major things changed in alpha10
- Declaring Permissions: https://developer.android.com/guide/health-and-fitness/health-connect/get-started#step_3_declare_permissions
- Requesting Permissions: https://developer.android.com/guide/health-and-fitness/health-connect/get-started#step_4_request_permissions_from_the_user
- Data types: https://developer.android.com/guide/health-and-fitness/health-connect/data-and-data-types/data-types#permissions
> Documentation and code changes are required to comply with these

## Store redirection / Permission Revoked
- If Health Connect is not installed users _might_ want to open the market - 
- If the permissions have been revoked twice, users _might_ want to open the Health Connect App
> maybe there should be code examples in the doc. I wouldn't implement it in the code (neither automatically nor as and optional param since it's out of scope).

## Get Permissions API
Since users can revoke access using the Health Connect App the SDK provides a function to get the current permissions (https://developer.android.com/guide/health-and-fitness/health-connect/get-started#step_4_request_permissions_from_the_user). As of now I'm just creating a useless request and using the exception response to tell if the access has been revoked.

--

I'm not that familiar with Kotlin but let me know if I can help with something.
Also, these are just suggestions/thoughts.

This issue can be closed at any time :)

**Comment by matinzd** [comment]
Hi @philipp65 

Thanks for your suggestions!

## Documentation Requirements

I noticed this yesterday and readme is updated if you check master branch.

## Documentation Requirements

Thanks. I might need to upgrade that in `gradle.properties` in the project so you don't need to add it in your own project and can be safely used without any changes in native code.

## Health Connect alpha10 migration

Alpha 10 migration has already happened. You can check [this commit](https://github.com/matinzd/react-native-health-connect/commit/6a2dd74ee5d91bd4aafc1a94084cd207fa3eaafd).

## Store redirection / Permission Revoked

I will try to review the APIs once again. There are more APIs that need to be implemented such as `getChanges ` and `getChangesToken` for data synchronization. https://developer.android.com/guide/health-and-fitness/health-connect/common-workflows/sync-data

## Get Permissions API

This will be added in the next version.

**Comment by philipp65** [comment]
Awesome, thanks for the clarifications and future enhancements 👍
