### ISSUE TITLE
Integration works on a test device when I run it, but does not work on a build from the play store

### ISSUE THREAD

**Issue by swaroopbutala** [matinzd/react-native-health-connect#32]
**Describe the bug**
The health connect integration works on a test device when I run and test it. But when I try to install it via Play Store it shows the following popup attached as a screen capture. 

**To Reproduce**
1. https://play.google.com/store/apps/details?id=com.fitpanda
2. Sign up and go on user profile and try to enable health connect. 

**Expected behavior**
1. It should show a prompt to enable steps in health connect as it shows on a test device.

![WhatsApp Image 2023-08-03 at 11 45 25 AM](https://github.com/matinzd/react-native-health-connect/assets/5388679/fcf22610-a5b6-400f-ba02-7588031a8793)

**Screencapture for the bug**
https://github.com/matinzd/react-native-health-connect/assets/5388679/0316905e-90f1-43ab-b1ab-2d8e428c2270

**Environment:**
 - Health Connect Version: (Latest for both health connect and [react-native-health-connect](https://github.com/matinzd/react-native-health-connect 1.1.0)
 - React Native Version: "0.70.5"
 - New architecture enabled: Yes

**Comment by matinzd** [comment]
If your app is released on Google Play, you must submit your declaration form. Read more about it here:

https://developer.android.com/guide/health-and-fitness/health-connect/frequently-asked-questions#request-access

https://docs.google.com/forms/d/1LFjbq1MOCZySpP5eIVkoyzXTanpcGTYQH26lKcrQUJo/viewform?edit_requested=true

**Comment by seanblonien** [comment]
I wasn't aware of the declaration form required for Play Store publishing -- could this comment you @matinzd wrote with awesome explanation be added to the README/documentation to more explicitly let developers know they must submit this form before publishing to the Play Store?

It'd be helpful to know so that developers could submit this form _before_ submitting to the play store, cause now I am blocked waiting on them to approve Health Connect for my app, when I could have submitted the form earlier if it was made clear it was necessary. I know it's not this package's responsibility, and yet it is a requirement to using this package in production.

**Comment by matinzd** [comment]
Hi @seanblonien,

That's a good idea and I will try to update the documents accordingly. However, I always tried to reference Google's documentation, it's better to always follow native platform documentation before implementing anything in React Native.

**Comment by seanblonien** [comment]
Thanks! And yea I'm learning that the hard way I guess 😅 

I'm new to mobile development thru Expo/React Native, and  wasn't aware there is a lot of dedicated work that still needs to be done on top of these modern abstractions for native features. And yet it really is so straightforward for a web developer like me to try out native app development now, so I appreciate you/this library! You are what has converted me to absolutely loving the ecosystem and community ❤️

**Comment by matinzd** [comment]
Mobile development can be tricky, even with Expo. There's a bunch of work and learning involved, from releasing apps to dealing with different phone quirks, performance stuff, and troubleshooting. Abstractions can make things confusing too. Figuring out what's wrong can be tough, whether it's in JS, Expo, or native code from RN core, especially for us as package maintainers.

**Comment by matinzd** [comment]
Thanks for all your support! 🌸
Mobile development can be tricky, even with Expo. There's a bunch of work and learning involved, from releasing apps to dealing with different phone quirks, performance stuff, and troubleshooting. Abstractions can make things confusing too. Figuring out what's wrong can be tough, whether it's in JS, Expo, or native code from RN core, especially for us as package maintainers will come in and we don't know if they are using Expo Go or Expo Dev Client or some old bare project :)
