### ISSUE TITLE
Crash issue in Android 13 devices 

### ISSUE THREAD

**Issue by chganesh** [matinzd/react-native-health-connect#33]
**Describe the bug**

When i can openHealthConnectSettings this method app crashed in android 13 

**To Reproduce**

**Expected behavior**
Need to open Health connect page 

**Screenshots**
![healthconnectissue](https://github.com/matinzd/react-native-health-connect/assets/14010143/5b820bb6-54d0-4580-90db-daa97cfd72de)

**Environment:**
 - "react-native-health-connect": "^1.1.0"
 - "react-native": "0.70.6"
 - New architecture enabled: No

**Comment by matinzd** [comment]
Did you follow the documentation here?

https://matinzd.github.io/react-native-health-connect/docs/permissions

**Comment by chganesh** [comment]
yes its working fine in Android 11 permission given. is there any possibility to install health connect automatically

**Comment by matinzd** [comment]
> yes its working fine in Android 11 permission given. after install health connect its working fine. is there any possibility to install health connect automatically.

Good to hear that. Health Connect app will be preinstalled on devices with Android 14.

**Comment by chganesh** [comment]
@matinzd Thank you. Below Android 14 devices what should we have to do. any solution
