### ISSUE TITLE
Add ExerciseRouteConsent

### ISSUE THREAD

**Issue by matinzd** [matinzd/react-native-health-connect#34]

**Comment by ugurakin1** [comment]
Hi, any ETA on this? I'm happy to contribute if it's not picked up yet.

**Comment by matinzd** [comment]
It's not picked up yet! I would be happy if you want to contribute.

**Comment by ugurakin1** [comment]
I also don't see a matching record on Android's [list of permissions](https://developer.android.com/health-and-fitness/guides/health-connect/plan/data-types#alpha10) but this might be the documentation being out of date. [Search yields a few results](https://developer.android.com/s/results/?q=read_exercise_routes).

**Comment by matinzd** [comment]
What do you mean?
