### ISSUE TITLE
"Service Not Available" Error during Initialization on emulators

### ISSUE THREAD

**Issue by virenradadiya** [matinzd/react-native-health-connect#38]
**Describe the bug**
I am encountering an error while trying to initialize the application using the initialize() function. The error message I receive is "Service not available." This issue occurs specifically when I'm running the application on an emulator.

**To Reproduce**
1. Launch the device emulator using react-native run-android.
2. Connect a watch emulator to the running device emulator.
3. Invoke the initialize() method to initiate the application.
4. Observe the error message displayed in the console:

**Screenshots**
![Screenshot 2023-08-21 at 4 05 53 PM](https://github.com/matinzd/react-native-health-connect/assets/30589064/2fdf867a-64d0-4ac9-90c9-6bd0e7fa3ef6)

**Additional Information:**
 -  have verified that the watch emulator is correctly connected to the device emulator by inspecting the development server's logs.
 - I've attempted to disconnect and reconnect the watch emulator, as well as restarting both the device and watch emulators, but the error persists.

**Comment by matinzd** [comment]
Make sure you have Health Connect app installed.
