### ISSUE TITLE
Add Gender and DateOfBirth

### ISSUE THREAD

**Issue by mariomurrent-softwaresolutions** [matinzd/react-native-health-connect#39]
Is it possible to add Gender and DateOfBirth?

**Comment by mphill** [comment]
I'm pretty sure Health Connect does not support this: 

https://developer.android.com/health-and-fitness/guides/health-connect/data-and-data-types/data-types#permissions

**Comment by mariomurrent-softwaresolutions** [comment]
Oh I must have mixed it with https://developer.android.com/health-and-fitness/guides/health-services/health-platform
which is deprecated.
