### ISSUE TITLE
Get All vitals 

### ISSUE THREAD

**Issue by chganesh** [matinzd/react-native-health-connect#40]
**Describe the bug**
How can i get last 7 days or 30 days or 6 months individual day steps count  calories count  heart rate ...etc 

Its not a bug need to get some informations 

**Environment:**
 -react-native-health-connect": "^1.1.0"
 - React Native Version: 0.72.1
 - New architecture enabled: No

**Comment by chganesh** [comment]
@matinzd Please help on this

**Comment by chganesh** [comment]
@matinzd  i am getting this issue while 

Error: Request rejected. Rate limited request quota has been exceeded. Please wait until quota has replenished before making further requests.
Error: Request rejected. Rate limited request quota has been exceeded. Please wait until quota has replenished before making further requests.

**Comment by matinzd** [comment]
Hi @chganesh,

I cannot help you with this kind of issues. You need to refer to the documentation on Google's website.

**Comment by chganesh** [comment]
thank you @matinzd.

How can i get last 7 days or 30 days or 6 months individual day steps count calories count heart rate ...etc

**Comment by matinzd** [comment]
Sorry I cannot help you with that. Your comment is not formatted properly and it's a logical programming question. You can solve it in different ways.
