### ISSUE TITLE
React-native cli android build fail after install lib

### ISSUE THREAD

**Issue by priyankacurio** [matinzd/react-native-health-connect#42]
**Describe the bug**
I have react native cli project with react naive version     "react-native": "0.70.1".

After installing lib through yarn -> yarn add react-native-health-connect@latest
I am not able to run android project getting below error -> 

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':react-native-health-connect:compileDebugAidl'.
> Could not resolve all task dependencies for configuration ':react-native-health-connect:debugCompileClasspath'.
   > Could not find com.facebook.react:react-native:.
     Required by:
         project :react-native-health-connect 

Is this lib not work for react-native cli project?

**Comment by matinzd** [comment]
Hi,

This lib works both of bare and expo projects.

**Comment by matinzd** [comment]
It seems your environment is not set up properly.

**Comment by matinzd** [comment]
Your emulator may not have sufficient storage. Please scroll up in log and find ADB and Gradle logs.
Closing it for now.
