### ISSUE TITLE
"Error: Error not specified" on insertRecords

### ISSUE THREAD

**Issue by gewfy** [matinzd/react-native-health-connect#43]
**Describe the bug**
I've managed to `initialize` and `requestPermission`, but when calling `insertRecords` it throws `[Error: Error not specified.]`. 

Please advise if there's any way to debug this from my end.

**To Reproduce**
1. Add 
```xml
<uses-permission android:name="android.permission.health.WRITE_EXERCISE"/>
```
2. Call 
```javascript
await initialize()
```
3. Call 
```javascript
await requestPermission([{accessType: 'write', recordType: 'ExerciseSession'}]);
```
4. Call
```javascript
await insertRecords([
    {
      recordType: 'ExerciseSession',
      exerciseType: 8,
      startTime: '2023-09-12T09:30:13.982Z',
      endTime: '2023-09-12T09:39:49.241Z',
    },
  ]);
```

**Expected behavior**
`insertRecords` should resolve without errors

**Environment:**
 - Health Connect Version: `1.2.0`
 - React Native Version: `0.69.9`
 - New architecture enabled: No

Thank you for a nice and well written library ☺️

**Comment by gewfy** [comment]
That's sort of the issue, it doesn't give any other clues. The JS error is nothing more than:
```
Error: Error not specified.
promiseMethodWrapper@
insertRecords@
generatorResume@[native code]
asyncGeneratorStep@
_next@
tryCallTwo@
doResolve@
Promise@
log@
generatorResume@[native code]
asyncGeneratorStep@
_next@
tryCallTwo@
doResolve@
Promise@
onPress@
_performTransitionSideEffects@
_receiveSignal@
onResponderRelease@
invokeGuardedCallbackProd@
invokeGuardedCallback@
invokeGuardedCallbackAndCatchFirstError@
executeDispatch@
executeDispatchesInOrder@
executeDispatchesAndRelease@
forEach@[native code]
forEachAccumulated@
runEventsInBatch@
runExtractedPluginEventsInBatch@
batchedUpdates$1@
batchedUpdates@
_receiveRootNodeIDEvent@
receiveTouches@
__callFunction@
__guard@
callFunctionReturnFlushedQueue@
callFunctionReturnFlushedQueue@[native code]
```

And in logcat I can't see anything of value:
```
09-12 15:20:45.445 25004 25181 D TrafficStats: tagSocket(151) with statsTag=0xffffffff, statsUid=-1
09-12 15:20:47.461 25004 25183 D TrafficStats: tagSocket(151) with statsTag=0xffffffff, statsUid=-1
09-12 15:20:47.986 25004 25049 D EGL_emulation: app_time_stats: avg=686.55ms min=9.16ms max=11326.09ms count=17
09-12 15:20:49.349 25004 25049 D EGL_emulation: app_time_stats: avg=681.80ms min=85.52ms max=1278.09ms count=2
09-12 15:20:49.449 25004 25074 E ReactNativeJS: [Error: Error not specified.]
09-12 15:20:49.465   407   553 D AudioFlinger: mixer(0xb400007bcf25d9a0) throttle end: throttle time(44)
09-12 15:20:49.467 25004 25188 D TrafficStats: tagSocket(173) with statsTag=0xffffffff, statsUid=-1
09-12 15:20:50.566   579   590 W System  : A resource failed to call release. 
09-12 15:20:50.566   579   590 W System  : A resource failed to call HardwareBuffer.close. 
09-12 15:20:50.566   579   590 W System  : A resource failed to call close. 
09-12 15:20:50.566   579   590 W System  : A resource failed to call release. 
09-12 15:20:51.480 25004 25193 D TrafficStats: tagSocket(151) with statsTag=0xffffffff, statsUid=-1
09-12 15:20:54.990   770   997 D EGL_emulation: app_time_stats: avg=2555.10ms min=10.14ms max=25313.38ms count=10
```

**Comment by matinzd** [comment]
Are you using latest version of Health Connect app?

**Comment by gewfy** [comment]
I believe so, installed it today
<img width="255" alt="image" src="https://github.com/matinzd/react-native-health-connect/assets/474066/94852fe5-7317-41dc-8e61-fd7421e71436">

I'm running it in Android emulator. Could that be an issue?

**Comment by matinzd** [comment]
> I'm running it in Android emulator. Could that be an issue?

No, I don't think so.

It seems it's an internal error from the health connect itself.

**Comment by gewfy** [comment]
Oh nice! Then I seem to have an old version. Will try to get the latest then.

Do you know if there's an official developer forum or issue tracker for the health connect project? Also noticed that `EXERCISE_TYPE_MEDITATION` is completely missing - but should probabaly be there since the refer a lot to those kinds of apps.
https://developer.android.com/reference/androidx/health/connect/client/records/ExerciseSessionRecord#summary

And thanks for the quick support, really appreciate it 🙌

**Comment by gewfy** [comment]
> Try to bump the `androidx.health.connect:connect-client` manually in your `node_modules` and see if that resolves the problem. Then I will create another release for that.

Sure will do!

**Comment by gewfy** [comment]
Yes works like a charm!
