### ISSUE TITLE
This release includes permissions that haven't been declared in Play Console

### ISSUE THREAD

**Issue by chganesh** [matinzd/react-native-health-connect#48]
**Describe the bug**
This release includes permissions that haven't been declared in Play Console. Go to Sensitive app permissions to update your permission declarations. [Learn more](https://support.google.com/googleplay/android-developer/answer/9214102)

Error
You need approval to use the following Health Connect permissions in your app:
android.permission.health.READ_ACTIVE_CALORIES_BURNED
android.permission.health.READ_HEART_RATE
android.permission.health.READ_STEPS
android.permission.health.READ_DISTANCE
android.permission.health.READ_FLOORS_CLIMBED

**To Reproduce**
While uploading app bundle to play store

**Expected behavior**

**Environment:**
 - Health Connect Version: 1.1.0
 - React Native Version: 0.72.4
 - New architecture enabled: No

**Comment by chganesh** [comment]
@matinzd  Please help me this one. thanks in advance

**Comment by matinzd** [comment]
Please read here: https://developer.android.com/health-and-fitness/guides/health-connect/publish/request-access

**Comment by mphill** [comment]
Google’s review process is beyond broke.  Good luck.
