### ISSUE TITLE
Cannot Seem to get Blood Pressure data 

### ISSUE THREAD

**Issue by AbdulHanan02** [matinzd/react-native-health-connect#52]
const readSampleDat = () => {
      readRecords('BloodPressure', {
        timeRangeFilter: {
          operator: 'between',
          startTime: '2023-12-05T10:00:00.405Z',
          endTime: '2023-12-05T23:53:15.405Z',
        },
      }).then((result) => {
        console.log('Retrieved records: ', JSON.stringify({ result }, null, 2));
      });

**Comment by matinzd** [comment]
I cannot help you with the provided information.
