### ISSUE TITLE
Execution failed for task ':react-native-health-connect:compileDebugKotlin'.

### ISSUE THREAD

**Issue by mujeeb98** [matinzd/react-native-health-connect#54]
I was attempting to add react-native-health-connect to our React Native app. After adding this library, I changed the minimum SDK to 26 and the compileSdkVersion to 34. Following these changes, the following error appeared:

<img width="591" alt="Screenshot 2024-01-09 at 2 56 00 PM" src="https://github.com/matinzd/react-native-health-connect/assets/101321919/4c19a2ea-c2fb-4c26-80f4-427a965a3e47">

1. Kotlin version 1.6.10
2."react-native": "0.71.5",

<img width="611" alt="Screenshot 2024-01-09 at 2 58 07 PM" src="https://github.com/matinzd/react-native-health-connect/assets/101321919/91cab0e7-bc30-46fe-91c7-958186fa7b53">
<img width="1137" alt="Screenshot 2024-01-09 at 2 58 46 PM" src="https://github.com/matinzd/react-native-health-connect/assets/101321919/e2972c61-7634-452a-884f-bad160e2415b">
<img width="801" alt="Screenshot 2024-01-09 at 2 59 38 PM" src="https://github.com/matinzd/react-native-health-connect/assets/101321919/abecb353-b8dc-4dd3-97ac-2dade8f1bc65">

 - Health Connect Version: 1.1.0
 - React Native Version: 0.71.5
 - New architecture enabled: Yes/No

**Comment by mujeeb98** [comment]
I changed kotlinVersion = '1.6.10' to kotlinVersion = '1.8.0', and added the @shopify/flash-list library with version 1.6.1. The application is now working fine.

**Comment by matinzd** [comment]
Then I mark this as resolved!
