### ISSUE TITLE
Nutrition Record: asking for permission and reading

### ISSUE THREAD

**Issue by jtli** [matinzd/react-native-health-connect#58]
I can't tell if I missed something, but when trying to ask for permission (using [requestPermission](https://matinzd.github.io/react-native-health-connect/docs/api/methods/requestPermission)) I couldn't find a record type that corresponds to Nutrition. I checked in src/types/records.types.ts for type HealthConnectRecord and Nutrition wasn't listed there.
Same thing with calling readRecords (using [readRecords](https://matinzd.github.io/react-native-health-connect/docs/api/methods/readRecords)).

Is it actually not supported, or if it is, how do I ask for permission and read nutrition?

**Comment by KesoGizmoYoshi** [comment]
I can see `NutritionRecord` in `records.types.ts`, but it is not included in `HealthConnectRecord`.

**Comment by matinzd** [comment]
Hello 👋,

You can see the implementation here:

https://github.com/matinzd/react-native-health-connect/blob/main/android/src/main/java/dev/matinzd/healthconnect/records/ReactNutritionRecord.kt

**Comment by matinzd** [comment]
UPDATE:

As we have a lot of data types, I forgot to expose `NutritionRecord` and `recordType`. I will send a patch very soon.
