### ISSUE TITLE
Sleep recordType value mismatch between methods

### ISSUE THREAD

**Issue by krisidmisso** [matinzd/react-native-health-connect#63]
**Describe the bug**
`requestPermission()` requires permission name as `SleepSession` and `getGrantedPermissions()`  returns `Sleep`
**To Reproduce**
1. Trigger `requestPermission([{accessType: 'read', recordType: 'SleepSession'}])`
2. Trigger `getGrantedPermissions()`
3. See permissions array from `getGrantedPermissions`

**Expected behavior**
`recordType` should match on both methods

**Screenshots**
<img width="920" alt="image" src="https://github.com/matinzd/react-native-health-connect/assets/9657055/5cc0f376-3699-4fdc-b116-17a791671d09">

**Environment:**
 - Health Connect Version: 1.2.3
 - React Native Version: 0.73.1
 - New architecture enabled: Yes

**Comment by matinzd** [comment]
It seems like this inconsistency comes from the health connect core. I will try to investigate this.

**Comment by RM-Smilamind** [comment]
Same for (at least):
ExerciseSession --> Exercise
HeartRateVariabilityRmssd -> HeartRateVariability
MenstruationFlow -> Menstruation

... and probably few others that I don't use

**Comment by ugurakin1** [comment]
Hi any ETA on this? I'm happy to contribute if it's not picked or you're able to hand over.

**Comment by ugurakin1** [comment]
Hey @matinzd, created a PR for a potential solution for this. If you could take a quick look whenever you can it would be grand, thanks in advance!

**Comment by matinzd** [comment]
This should be fixed in v3.1.1.
