### ISSUE TITLE
Question: Synchronise Data

### ISSUE THREAD

**Issue by prateek041** [matinzd/react-native-health-connect#72]
I see that Health connect provides functionality to regularly synchronise data. Can this library work with that ? or I would have to come up with my own implementations ?

ref: [Synchronise Data](https://developer.android.com/health-and-fitness/guides/health-connect/develop/sync-data)

**Comment by matinzd** [comment]
Hey!

Not for now at least. It's in the todo list and I haven't found time to start implementing it. Feel free to fork the project and add it yourself or open a pull request.

**Comment by RM-Smilamind** [comment]
Hi @matinzd 

Any ETA on this, just to understand if I should wait for it or implement an alternative workflow until it's done?

Thanks

**Comment by Georg7** [comment]
> Hey!
> 
> 
> 
> Not for now at least. It's in the todo list and I haven't found time to start implementing it. Feel free to fork the project and add it yourself or open a pull request.

@matinzd any progress on that?

**Comment by matinzd** [comment]
Hello!

Therer are two PRs merged which is gonna be a breaking change. These will be included in v3 🚀

**Comment by Georg7** [comment]
Awesome and is there and eta for v3?

**Comment by matinzd** [comment]
This is now included in [v3](https://github.com/matinzd/react-native-health-connect/releases/tag/v3.0.0) and above 🚀 

Let me know if there are any issues.
