### ISSUE TITLE
Question: It is not possible to retrieve activityType/activityName

### ISSUE THREAD

**Issue by bbaryn** [matinzd/react-native-health-connect#76]
**Describe the bug**
In GoogleFit, it was possible to download the type of activity, by which we could distinguish whether the activity was running, walking or cycling. Has such functionality not been implemented? Or did google itself not add such a capability? It is also possible that it is available, but I cannot find it. Help

**Screenshots**
![image](https://github.com/matinzd/react-native-health-connect/assets/39910546/427fe987-54b3-44d2-9c0a-4a7b5d1d0a56)

**Environment:**
 - Health Connect Version: 2.0.1
 - React Native Version: 0.73.4
 - New architecture enabled: Yes

**Comment by KesoGizmoYoshi** [comment]
Have you tried 'ExerciseSession' as the recordType when using readRecord/readRecords?

**Comment by marlin34** [comment]
No, because I want to know what kind of the activity is assign to covered distance. In GoogleFit the distance was always returned with the activity type. This is not the case here and I wanted to know what the reason was :)

**Comment by bbaryn** [comment]
Anyone?

**Comment by matinzd** [comment]
This is a different platform where you can read what other applications have put in. Google Fit has a different purpose. Health Connect acts like a hub. 
I don't think you can acheive something like that with this library. Read more about it in the Google's documentation. If there is something that can be implemented, let me know.
