### ISSUE TITLE
Latest changes are not released 

### ISSUE THREAD

**Issue by 4yki** [matinzd/react-native-health-connect#8]
Hey @matinzd !... 

Thanks for the lib.
Right now I can't use changes from your last commit where you've migrated to the latest Health connect SDK and added few more methods to RN module.

Is it possible to have new version released ?
Thx!

**Comment by matinzd** [comment]
Changes are now available under alpha 7. https://github.com/matinzd/react-native-health-connect/releases/tag/v0.1.0-alpha.7
