### ISSUE TITLE
UNKNOWN_ERROR: java.lang.Class<oh.k0> cannot be instantiated

### ISSUE THREAD

**Issue by oscarparedez** [matinzd/react-native-health-connect#89]
My app works well on locally: permissions are requested properly and data is collected properly. However, on release builds, when trying to call `readRecords` function and attempt to collect data, I get the following error:

`{"nativeStackAndroid":[],"userInfo":null,"message":"java.lang.Class<oh.k0> cannot be instantiated","code":"UNKNOWN_ERROR"}`

I have already submitted a request to Google asking for them to allow my app to work with the health data, and it was approved a couple of days ago. Perhaps there's something missing on that process for me to be able to read records in a release build?

**Comment by matinzd** [comment]
Hello!

I guess you need to have the new version approved on Google Play in order for the release build to work. You can send it to review and have it approved but turn on managed publishing. Then try again and let us know!

**Comment by oscarparedez** [comment]
I'll submit my new build to Google Play and let you know If that solves the issue. Thank you :)

**Comment by oscarparedez** [comment]
> Hello!
> 
> I guess you need to have the new version approved on Google Play in order for the release build to work. You can send it to review and have it approved but turn on managed publishing. Then try again and let us know!

Update. I got a build approved by Google Play on May 9th. However, I am still getting the same error. It only happens in release builds, not in local build. Any thoughts?

**Comment by oscarparedez** [comment]
Added the following line to android/app/proguard-rules.pro

`-keep class dev.matinzd.healthconnect.records.** { *; }`

**Comment by matinzd** [comment]
Thanks for your update! That really makes sense given that you have enabled proguard. Since we do not use classes directly on the compile time, proguard will shrink all the record classes for the optimization. I am gonna release a new version and you can remove the proguard rules from your application!
