### ISSUE TITLE
How to setup the library when using Wix react-native-navigation?

### ISSUE THREAD

**Issue by predescu** [matinzd/react-native-health-connect#90]
**Describe the bug**
I'm struggling to set up the library on my React Native App. I'm using Wix react-native-navigation, and it looks like there is a type mismatch.
It would be great if we have an example for this scenario.

In this case, the MainActivity extends NavigationActivity instead of ReactActivity

**Screenshots**
![Screenshot 2024-05-02 at 14 46 32](https://github.com/matinzd/react-native-health-connect/assets/2477691/a2d44658-ca89-4547-9108-c7c7165aade0)

**Environment:**
 - Health Connect Version: 2.0.1
 - React Native Version: 0.73.5
 - New architecture enabled: No

**Comment by matinzd** [comment]
Hey!

Thanks for noticing this. Can you please share a minimal reproducible so I can work on it? Thanks :)

**Comment by predescu** [comment]
Hey @matinzd 
I've put together a minimal reproducible code (reactnative + react-native-navigation + react-native-health-connect). 
You can fid it at this location:
https://github.com/predescu/rnn-health-connect

I've commented out the updates on the android/app/src/main/java/com/rnnhealthconnect/MainActivity.kt file so the app can start.

On the screen, there si a button to request the permissions. When you press the button, the app will crash because the  HealthConnectPermissionDelegate.setPermissionDelegate(this) code line is missing from the MainActivity.kt

**Comment by cribcutkiran** [comment]
I've run into the same issue. RNN's NavigationActivity extends AppCompatActivity rather than ReactActivity. Anything that extends from ComponentActivity will have `registerForActivityResult()`, so could `setPermissionDelegate` just accept a ComponentActivity?
