### ISSUE TITLE
Support for Bridgeless react-native

### ISSUE THREAD

**Issue by seanblonien** [matinzd/react-native-health-connect#92]
**Describe the bug**
The plugin fails to load when the bridgeless architecture is enabled.

**To Reproduce**
I discovered this using Expo, so I will specify Expo repo steps, altho I imagine this may be an issue with bare react-native too
1. Have Expo 51 SDK project
2. Add "react-native-health-connect" as a dependency
3. Enable the new bridgeless mode by changing the app.config.ts file, as [documented clearly here in Expo documentation](https://docs.expo.dev/guides/new-architecture/#enable-the-new-architecture-in-an-existing-project)
4. Run `expo run:ios` to run a native build
    - I do think it's interesting to note even though this plugin is obviously only Android, it broke the ios build. so also figured there may be an underlying issue there.
6. The app never registered and loaded. See the error bellow and the app not load past the splash screen

**Expected behavior**
The app should load without issue with the bridgeless architecture enabled

**Screenshots**
Here is the error log I got:

```sh
[RedactedProjectName] Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'HealthConnect' could not be found. Verify that a module by this name is registered in the native
binary.Bridgeless mode: true. TurboModule interop: true. Modules loaded:
{"NativeModules":[],"TurboModules":["PlatformConstants","LogBox","SourceCode","AppState","BlobModule","WebSocketModule","SettingsManager","DevSettings","Networking","RedBox","Appearance","DevLoadingView","DeviceInfo","ImageLoader","LinkingManager","ReanimatedModule","NativeAnimatedTurboModule","KeyboardObserver","RNCSafeAreaContext","I18nManager","RNCAsyncStorage"],"NotFound":["NativePerformanceCxx","NativePerformanceObserverCxx","BugReporting","HeadlessJsTaskSupport","SoundManager","IntentAndroid","NativeReactNativeFeatureFlagsCxx","FrameRateLogger","PlatformLocalStorage","RNC_AsyncSQLiteDBStorage","HealthConnect"]}
[RedactedProjectName] Invariant Violation: "main" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called.
```

**Environment:**
 - Health Connect Version: 2.0.2
 - React Native Version: 0.74.1
 - New architecture enabled: Yes

**Comment by matinzd** [comment]
Hey!

I don't think this should happen since we also support new architecture. There might be some changes in React Native core or Expo that has caused this issue. Seems like the new Bridgeless mode requires some changes. For iOS, you should not have any issues using it there since we do not have auto linking set up for iOS.
I will investigate and update you when I find some time.

**Comment by seanblonien** [comment]
Hm turns out there must have been something misconfigured in my Expo project, not exactly sure what, but extremely likely an Expo thing

I upgrading Expo packages and cleared out cache which fixed it. apologies for not trying to get a minimal working case _first_, I probably would have saved some time if I tried to reproduce it more minimally

**Comment by matinzd** [comment]
Hey @seanblonien 

Working on a new expo plugin for health connect. Feel free to try it out in your project and let me know what you think.

https://github.com/matinzd/expo-health-connect
