### ISSUE TITLE
Question: is Library only for expo?

### ISSUE THREAD

**Issue by nestorLanex2** [matinzd/react-native-health-connect#96]
Hi! I am yet to migrate into this library from Google fit. 

So far I'm seeing the expo installation segment but my current project is on bare react native. 
Are there steps I needed to do in order to properly setup the library that is not part of the current Readme? 

I tried running the sample code and i tried to check the grantedPermissions section (as in the example code) but it shows empty.

**Comment by matinzd** [comment]
No. This library works with CLI template as well.

**Comment by nestorLanex2** [comment]
@matinzd Thanks for clarifying !
